gui_port: 8080
api_port: 9080

settings_file: <%= ENV['HOME'] %>/coyoho-settings.yml

auto_login:
  username: admin
  password: admin

# auto_login:
  # username: user
  # password: user

logger:
  XBeeConnectionState:
    level: :info
